apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "cGFzc3dvcmQxMjM="
  MYSQL_DATABASE: "bXlkYg=="
  MYSQL_USER: "ZGItdXNlcg=="
  MYSQL_PASSWORD: "cGFzc3dvcmQxMjM="